plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag : tag-archive
    category: category-archive
  permalinks:
    tag: archives/tag/:name/
    category: archives/category/:name/