plugins:
- jekyll-archives

excerpt_separator: <!-- Plus -->

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'

